site_name: "VASP workshop"
site_url: https://example.com/

nav:
  - Introduction: 'index.md'
  - Interactive Job: 'interactive_job.md'
  - GPU calculation: 'GPU_calulation.md'
  - H2O machine learning: 'H2O_machine_learning_MD.md'
  - Parallel NEB: 'parallel_NEB.md'
  - Very parallel: 'very_parallel.md'


markdown_extensions:
  - admonition

